name: Publish Docker Image

on:
  push:
    tags:
      - 'v*'  # Dispara cuando se crea un tag que comience con "v"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.IVANGALLEGO13 }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: |
          TAG=${GITHUB_REF##*/}
          docker build -t IvanGallego13/RetoDocker1:${TAG} .

      - name: Push Docker image
        run: |
          TAG=${GITHUB_REF##*/}
          docker push IvanGallego13/RetoDocker1:${TAG}
